### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by RangerMauve** [xytis/GURPS#2]
Hi, this project looks super handy and I'd really like to make use of it to make a character sheet app. Would you mind adding a license to the project (maybe MIT?) so that people can know how it could be used?

**Comment by RangerMauve** [comment]
Whoopes! Looks like this is just using [the gcs_library](https://github.com/richardwilkes/gcs_library) files which has a clear license. This happened to come up first in the google search. Sorry!

**Comment by xytis** [comment]
Yeah, it's an extended copy of gcs library, plus some custom definitions that came up from personal campaigns. If you plan on investing development effort in character sheet app -- please consider contributing to GCS.

**Comment by RangerMauve** [comment]
I want to make something that works on mobile phones through the web, so I don't think that GCS is what I need. Though the library seems like it will be super useful and I plan to use the format (as well as being able to export custom rules to the same format).

**Comment by xytis** [comment]
Great idea. I had the same few years back, but never found the time to do it. If you want -- I can provide my feedback on your project :) I got several decades of experience in development :D

**Comment by RangerMauve** [comment]
That would be awesome, thank you! I'm new to GURPS so I was going to start by making it faster to do the initial character creation. I'll ping you once I have some of it put together. :D

**Comment by xytis** [comment]
I recently made a paper version of 'easy mode' character creation. It included a simple choice of equipment set, with corresponding skills via paper cards (think as 'class' selection, i.e. mage, rogue, warrior, clerk), then people had to choose advantages from another deck of small paper cards to match a max allowed point total (20 in last case) and randomly draw disadvantages from multiple piles labeled by disadvantage cost (-5, -10, -15) to a maximum disadvantage number (-20 in last case)

**Comment by RangerMauve** [comment]
That's really cool!

My goal for now is to load the basic set for all advantages/disadvantages/etc and have lists with a count of how many points you have left.

I want to make it easy to filter between the types in the various sections to speed things up.

I think I'll have the initial points configurable so that people have more options for their campaigns (maybe have a drop-down with the values suggested in the book).

**Comment by xytis** [comment]
Sounds good. Well, I'll wait for your project code then :)

**Comment by xytis** [comment]
Also, which programing languages you want to use?

**Comment by RangerMauve** [comment]
I'm planning on making this a fully-offline single page web application, so I'll be using JavaScript.

The goal is for people to open a link on any device they have and get started without having to install anything.

I'll be using the new Progressive Web Application APIs in modern browsers so that it can work offline and be added to people's desktops as application icons so it'll feel like a regular app.
